on:
  push:
    branches:
      - master
    tags:
      - '*'
  workflow_dispatch:
  # For quickly detecting important differences in runner configurations

name: alfred-workflow

env:
  RELEASE_COMMIT: ${{ github.ref_type == 'tag' }}
  OSX_SDK_VERSION: 11.1
  PINBOARD_TOKEN: ${{ secrets.PINBOARD_TOKEN }}

jobs:
  check_if_tagged:
    # A commit on master that's tagged will trigger the next job twice!
    # Once for master commit and once for tag commit. To avoid this, we wil
    # figure out if the commit is tagged.
    # If it is, the next job will only be triggered for tag commit.
    # (for only ref_type='tag') and not the master commit.
    # If it is not tagged, then outputs.istagged=0, which will allow a
    # master commit/event to run the next job
    name: Check if tagged
    strategy:
      matrix:
        os: [macos-11, macos-12]
        rust: [1.65.0, stable]
        exclude:
          - os: macos-12
            rust: 1.65.0

    runs-on: ${{ matrix.os }}
    outputs:
      istagged: ${{ steps.master_is_tagged.outputs.tagged }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Check if commit is tagged
        id: master_is_tagged
        # git fetch --prune --unshallow --tags
        run: |
          cd ${{ github.workspace }}
          value=$(git describe --tags --abbrev=0 --exact-match ${{ github.sha }}) || true
          [ -n "$value" ] && value=1 || value=0
          echo "tagged=$value" >> $GITHUB_OUTPUT
  build_universal:
    name: Build Universal Binary
    strategy:
      matrix:
        os: [macos-11, macos-12]
        rust: [1.65.0, stable]
        exclude:
          - os: macos-12
            rust: 1.65.0
    runs-on: ${{ matrix.os }}
    needs: check_if_tagged
    if: ${{ needs.check_if_tagged.outputs.istagged == 0 || github.ref_type == 'tag' }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: aarch64-apple-darwin
          override: true

      - name: Show macOS Version
        run: sw_vers
      - name: Set SDKROOT
        run: echo "SDKROOT=$(xcrun -sdk macosx$OSX_SDK_VERSION --show-sdk-path)" >> $GITHUB_ENV
      - name: Set MACOSX_DEPLOYMENT_TARGET
        run: echo "MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx$OSX_SDK_VERSION --show-sdk-platform-version)" >> $GITHUB_ENV
      - name: Build aarch64-apple-darwin (Debug)
        uses: actions-rs/cargo@v1
        if:  ${{ env.RELEASE_COMMIT != 'true' }}
        with:
          command: build
          args: --target aarch64-apple-darwin
      - name: Build aarch64-apple-darwin (Release)
        uses: actions-rs/cargo@v1
        if: ${{ env.RELEASE_COMMIT == 'true' }}
        with:
          command: build
          args: --release --target aarch64-apple-darwin

      - name: Build x86_64-apple-darwin (Debug)
        uses: actions-rs/cargo@v1
        if: ${{ env.RELEASE_COMMIT != 'true' }}
        with:
          command: build
          args: --target x86_64-apple-darwin
      - name: Build x86_64-apple-darwin (Release)
        uses: actions-rs/cargo@v1
        if: ${{ env.RELEASE_COMMIT == 'true' }}
        with:
          command: build
          args: --release --target x86_64-apple-darwin

      - name: Grow fat, test, and make alfredworkflow (if it's a tag event)
        run: .github/workflows/script.sh

      - name: Upload for release
        id: upload_artifact
        uses: actions/upload-artifact@v2
        if: ${{ github.ref_type == 'tag' && matrix.rust == 'stable' && matrix.os == 'macos-11' }}
        with:
          name: workflow-upload
          path: AlfredPinboardRust-${{ github.ref_name }}.alfredworkflow

  release_alfred:
    name: Release Workflow
    runs-on: macos-11
    needs: build_universal
    if: ${{ github.ref_type == 'tag' }}
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: workflow-upload
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: AlfredPinboardRust-${{ github.ref_name }}.alfredworkflow
